<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $title ?? $heading ?? 'Administration' }} · Pulse CMS</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body><a class="p-skip-link" href="#main-content">Skip to main content</a><div class="p-shell">
<aside class="p-sidebar" id="admin-navigation" data-drawer aria-label="Administration navigation"><a class="p-brand" href="{{ auth()->user()->can('dashboard.view') ? route('admin.dashboard') : route('admin.profile.edit') }}"><span class="p-brand-mark" aria-hidden="true">P</span><span>Pulse CMS</span></a>
<nav class="p-nav" aria-label="Primary">
<div class="p-nav-group"><p class="p-nav-label">Workspace</p>@can('dashboard.view')<a href="{{ route('admin.dashboard') }}" @if(request()->routeIs('admin.dashboard')) aria-current="page" @endif>Dashboard</a>@endcan @can('pages.manage')<a href="{{ route('admin.pages') }}" @if(request()->routeIs('admin.pages*')) aria-current="page" @endif>Pages</a>@endcan @can('posts.manage')<a href="{{ route('admin.posts') }}" @if(request()->routeIs('admin.posts*')) aria-current="page" @endif>Posts</a>@endcan @can('media.manage')<a href="{{ route('admin.media') }}" @if(request()->routeIs('admin.media*')) aria-current="page" @endif>Media</a>@endcan @can('taxonomy.manage')<a href="{{ route('admin.categories') }}" @if(request()->routeIs('admin.categories*','admin.tags*')) aria-current="page" @endif>Taxonomy</a>@endcan @can('menus.manage')<a href="{{ route('admin.menus') }}" @if(request()->routeIs('admin.menus*')) aria-current="page" @endif>Menus</a>@endcan @can('forms.manage')<a href="{{ route('admin.forms') }}" @if(request()->routeIs('admin.forms*')) aria-current="page" @endif>Forms</a>@endcan</div>
<div class="p-nav-group"><p class="p-nav-label">Access</p>@can('users.manage')<a href="{{ route('admin.users.index') }}" @if(request()->routeIs('admin.users.*')) aria-current="page" @endif>Users</a>@endcan @can('roles.manage')<a href="{{ route('admin.roles.index') }}" @if(request()->routeIs('admin.roles.*')) aria-current="page" @endif>Roles</a>@endcan <a href="{{ route('admin.mfa.show') }}" @if(request()->routeIs('admin.mfa.*')) aria-current="page" @endif>Security</a></div>
<div class="p-nav-group"><p class="p-nav-label">Commerce</p>@can('commerce.products.manage')<a href="{{ route('admin.commerce.products.index') }}">Catalogue</a>@endcan @can('commerce.inventory.manage')<a href="{{ route('admin.commerce.inventory.index') }}">Inventory</a>@endcan @can('commerce.orders.manage')<a href="{{ route('admin.commerce.orders.index') }}">Orders</a>@endcan @can('commerce.payments.manage')<a href="{{ route('admin.commerce.payments.index') }}">Payments</a>@endcan</div>
<div class="p-nav-group"><p class="p-nav-label">Platform</p>@can('themes.manage')<a href="{{ route('admin.themes') }}" @if(request()->routeIs('admin.themes*')) aria-current="page" @endif>Themes</a>@endcan @can('plugins.manage')<a href="{{ route('admin.plugins') }}" @if(request()->routeIs('admin.plugins*')) aria-current="page" @endif>Plugins</a>@endcan @can('seo.manage')<a href="{{ route('admin.seo') }}" @if(request()->routeIs('admin.seo*')) aria-current="page" @endif>SEO</a>@endcan @can('settings.manage')<a href="{{ route('admin.settings') }}" @if(request()->routeIs('admin.settings*')) aria-current="page" @endif>Settings</a>@endcan</div>
</nav></aside><button type="button" class="p-overlay" data-drawer-overlay aria-label="Close navigation"></button>
<div class="p-shell-main"><header class="p-topbar"><div class="p-topbar-actions"><button type="button" class="p-button p-button--subtle p-icon-button p-mobile-toggle" data-drawer-toggle aria-controls="admin-navigation" aria-expanded="false"><span aria-hidden="true">☰</span><span class="sr-only">Open navigation</span></button><strong>{{ $heading ?? 'Administration' }}</strong></div><details class="p-user-menu"><summary class="p-button p-button--secondary"><span class="p-topbar-user-name">{{ auth()->user()->name }}</span><span aria-hidden="true">⌄</span></summary><div class="p-dropdown"><a href="{{ route('admin.profile.edit') }}">Profile and sessions</a><a href="{{ route('admin.mfa.show') }}">MFA and security</a><form method="POST" action="{{ route('admin.logout') }}">@csrf<button type="submit">Sign out</button></form></div></details></header>
<main class="p-content" id="main-content" tabindex="-1">@yield('content')</main></div></div><x-pulse.toasts/><x-pulse.confirm-dialog/><div id="pulse-progress" role="status" aria-live="polite" class="sr-only"></div></body></html>
