<?php

namespace Database\Seeders;

use App\Models\Plugin;
use Illuminate\Database\Seeder;

class PulsePluginSeeder extends Seeder
{
    public function run(): void
    {
        $plugins = [
            [
                'name' => 'Blog',
                'slug' => 'blog',
                'category' => 'content',
                'icon' => 'article',
                'description' => 'Adds posts, categories, tags, authors, excerpts, scheduled publishing, and blog layouts.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['posts', 'categories', 'tags', 'authors'],
            ],
            [
                'name' => 'SEO Toolkit',
                'slug' => 'seo-toolkit',
                'category' => 'marketing',
                'icon' => 'query_stats',
                'description' => 'Adds meta tags, Open Graph, Twitter cards, sitemap tools, robots.txt controls, and SEO previews.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['seo', 'sitemap', 'robots', 'social-preview'],
            ],
            [
                'name' => 'Security Center',
                'slug' => 'security-center',
                'category' => 'security',
                'icon' => 'shield_lock',
                'description' => 'Adds login protection, admin security options, activity alerts, and basic hardening checks.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['login-security', 'audit', 'lockout'],
            ],
            [
                'name' => 'Site Health',
                'slug' => 'site-health',
                'category' => 'system',
                'icon' => 'monitor_heart',
                'description' => 'Checks database, storage, cache, mail, permissions, PHP version, and common deployment issues.',
                'is_active' => true,
                'has_settings' => false,
                'provides' => ['health-checks', 'diagnostics'],
            ],
            [
                'name' => 'Error Log Viewer',
                'slug' => 'error-log-viewer',
                'category' => 'system',
                'icon' => 'bug_report',
                'description' => 'Displays readable application errors, timestamps, pages, context, and admin-friendly debugging notes.',
                'is_active' => true,
                'has_settings' => false,
                'provides' => ['logs', 'error-viewer'],
            ],
            [
                'name' => 'Forms Builder',
                'slug' => 'forms-builder',
                'category' => 'forms',
                'icon' => 'dynamic_form',
                'description' => 'Adds custom forms, submissions, email notifications, spam protection, and form widgets.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['forms', 'submissions', 'notifications'],
            ],
            [
                'name' => 'Analytics',
                'slug' => 'analytics',
                'category' => 'analytics',
                'icon' => 'analytics',
                'description' => 'Tracks page views, top pages, referrers, devices, browsers, and basic content performance.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['traffic', 'reports'],
            ],
            [
                'name' => 'Popup Builder',
                'slug' => 'popup-builder',
                'category' => 'marketing',
                'icon' => 'web_asset',
                'description' => 'Adds newsletter popups, announcements, cookie notices, promos, and exit-intent rules.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['popups', 'rules'],
            ],
            [
                'name' => 'Backup & Restore',
                'slug' => 'backup-restore',
                'category' => 'system',
                'icon' => 'backup',
                'description' => 'Exports and restores content, settings, theme configurations, and plugin configuration data.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['backup', 'restore'],
            ],
            [
                'name' => 'Maintenance Mode',
                'slug' => 'maintenance-mode',
                'category' => 'system',
                'icon' => 'construction',
                'description' => 'Adds custom maintenance screens, countdowns, allowlists, and friendly downtime pages.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['maintenance'],
            ],
            [
                'name' => 'Redirect Manager',
                'slug' => 'redirect-manager',
                'category' => 'seo',
                'icon' => 'alt_route',
                'description' => 'Adds 301/302 redirects, broken link tracking, and SEO migration support.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['redirects', 'broken-links'],
            ],
            [
                'name' => 'Static HTML Exporter',
                'slug' => 'static-html-exporter',
                'category' => 'export',
                'icon' => 'archive',
                'description' => 'Exports the public site as a full static HTML/CSS/JS zip package.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['html-export', 'zip-export'],
            ],
            [
                'name' => 'Resend Mailer',
                'slug' => 'resend-mailer',
                'category' => 'mail',
                'icon' => 'outgoing_mail',
                'description' => 'Adds Resend email delivery configuration for system, form, registration, and notification emails.',
                'is_active' => false,
                'has_settings' => true,
                'provides' => ['mail', 'resend'],
            ],
            [
                'name' => 'SMTP Mailer',
                'slug' => 'smtp-mailer',
                'category' => 'mail',
                'icon' => 'mail',
                'description' => 'Adds SMTP configuration for shared hosting and traditional email providers.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['mail', 'smtp'],
            ],
            [
                'name' => 'Stripe Payments',
                'slug' => 'stripe-payments',
                'category' => 'payments',
                'icon' => 'payments',
                'description' => 'Adds Stripe key configuration and payment display support for checkout-enabled themes.',
                'is_active' => false,
                'has_settings' => true,
                'provides' => ['payments', 'stripe'],
            ],
            [
                'name' => 'Paystack Payments',
                'slug' => 'paystack-payments',
                'category' => 'payments',
                'icon' => 'account_balance_wallet',
                'description' => 'Adds Paystack key configuration for African-friendly payment workflows.',
                'is_active' => false,
                'has_settings' => true,
                'provides' => ['payments', 'paystack'],
            ],
            [
                'name' => 'Crypto Payments',
                'slug' => 'crypto-payments',
                'category' => 'payments',
                'icon' => 'currency_bitcoin',
                'description' => 'Adds crypto payment provider settings for global payment support.',
                'is_active' => false,
                'has_settings' => true,
                'provides' => ['payments', 'crypto'],
            ],
            [
                'name' => 'Ecommerce',
                'slug' => 'ecommerce',
                'category' => 'commerce',
                'icon' => 'storefront',
                'description' => 'Adds products, product pages, carts, checkout structure, and order foundations.',
                'is_active' => false,
                'has_settings' => true,
                'provides' => ['products', 'cart', 'orders'],
                'requires' => ['stripe-payments|paystack-payments|crypto-payments'],
            ],
            [
                'name' => 'Business Website',
                'slug' => 'business-website',
                'category' => 'site-type',
                'icon' => 'business_center',
                'description' => 'Adds service pages, company sections, team blocks, CTA sections, and lead-generation defaults.',
                'is_active' => true,
                'has_settings' => true,
                'provides' => ['business-pages', 'services'],
            ],
            [
                'name' => 'School Website',
                'slug' => 'school-website',
                'category' => 'site-type',
                'icon' => 'school',
                'description' => 'Adds school pages, admissions sections, courses, events, announcements, and gallery foundations.',
                'is_active' => false,
                'has_settings' => true,
                'provides' => ['school-pages', 'courses', 'events'],
            ],
        ];

        foreach ($plugins as $plugin) {
            Plugin::updateOrCreate(
                ['slug' => $plugin['slug']],
                $plugin
            );
        }
    }
}
